name: Deploy

on: push

env:
  TF_VERSION: 1.3.7
  TG_VERSION: 0.46.2
  WORK_DIR: terraform/user_resources
  STATE_BUCKET: ${{ secrets.STATE_BUCKET }}
  ENVIRONMENT: ${{ github.actor }}

jobs:
  PushImage:
    runs-on: ubuntu-latest
    outputs:
        image_url: ${{ steps.docker_push.outputs.image_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push Docker image
        id: docker_push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f docker/nginx/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image_url=${ECR_REGISTRY}/${ECR_REPOSITORY}" >> "$GITHUB_OUTPUT"
  Deploy:
    runs-on: ubuntu-latest
    needs: PushImage
    env:
      IMAGE_URL: ${{ needs.PushImage.outputs.image_url }}
    steps:
        - name: Checkout
          run: |
            echo "${{ needs.PushImage.outputs.image_url }}"
            echo $IMAGE_URL