name: Test

on: 
  push:

env:
  TF_VERSION: 1.3.7
  TG_VERSION: 0.43.0
  WORK_DIR: terraform/user_resources
  STATE_BUCKET: ${{ secrets.STATE_BUCKET }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
    - name: test
      run: |
        echo $STATE_BUCKET
        echo $WORK_DIR
    - name: test
      run: |
        echo "NAME=hoge" >> $GITHUB_ENV
    - name: debug
      id: step1
      run: echo "test=world" >> "$GITHUB_OUTPUT"
  build2:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: test
      run: |
        echo $NAME
        echo ${{ env.NAME }}
    - env:
        OUTPUT1: ${{needs.build.outputs.output1}}
      run: echo $OUTPUT1

