name: Test

on: 
  push:

env:
  TF_VERSION: 1.3.7
  TG_VERSION: 0.43.0
  WORK_DIR: terraform/user_resources
  STATE_BUCKET: ${{ secrets.STATE_BUCKET }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        echo $STATE_BUCKET
        echo $WORK_DIR
